# ################              == ATENÇÃO ==              ################
# SOFTWARE LICENCIADO - PARA QUE O PLUGIN POSSA EXECUTAR É PRECISO CONEXÃO
# COM A INTERNET DURANTE A INICIAZAÇÃO DO SERVIDOR E UMA LICENÇA VÁLIDA.
# Exemplo:
# licenca: 'XXXXXXXXXXXXXXXX'
# Coloque a sua licença abaixo:
licenca: ''

# Configurações relacionadas ao MySQL.
mysql:
  # Caso 'enable: true' e a conexão seja feita o SQLite será desabilitado e os dados não serão atualizados nele.
  # Utilize /statsadm <importar/exportar>
  # Importar = copiar do MySQL para o SQLite sobreescrevendo as atualizações.
  # Exportar = copiar do SQLite para o MySQL sobreescrevendo as atualizações.
  enable: false
  host: 'localhost'
  port: 3306
  database: 'playerkillstats'
  user: 'username'
  password: 'pass'